//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_shorts
    {
        public int id { get; set; }
        public string Naimenovanie { get; set; }
        public string Tip { get; set; }
        public int Kolichestvo_v_upakovke { get; set; }
        public string Edinitsa_izmerenia { get; set; }
        public int Nasclade { get; set; }
        public int Ostatok { get; set; }
        public int stoimost { get; set; }
    }
}
