//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_material
    {
        public int id { get; set; }
        public string Produkcia { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
    }
}
