//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_s_import
    {
        public string Наименование_продукции { get; set; }
        public int Артикул { get; set; }
        public string Минимальная_стоимость_для_агента { get; set; }
        public string Изображение { get; set; }
        public string Тип_продукции { get; set; }
        public string Количество_человек_для_производства { get; set; }
        public string Номер_цеха_для_производства { get; set; }
    }
}
